AdityaSinha2305/ForkTheCaptcha

- js/script.js
Hi@AdityaSinha2305,
This pull request adds a confirmation alert to verify if the entered captcha is correct or not
Please review the changes and provide feedback.
> ISSUE#9 Make submit button responsive 

- index.html
- styles/style.css
as said the image is now added in the html only
Kindly review this code and mention if any changes are needed
> bg added in html

- index.html
- styles/style.css
> Changed background color of footer to full-width

- js/script.js
Now the captcha be submitted even when the enter key is clicked.
kindly go through the changes and merge it if everything looks fine.
> Added a event listener when keydown is Enter

- styles/style.css
Changes:
Adjusted the text color, background color, border, font size, and added a hover effect to the start button.
Reasoning:
I believe that these changes will improve the overall appearance and usability of the start button. The new text color and background color will make the button more visually appealing, and the border, font size, and hover effect will make it easier to use.
Testing:
I have tested these changes on my local machine and they appear to be working as expected.
Additional notes:
Please let me know if you have any questions or concerns.
I hope this helps!
> make changes in start button

- styles/style.css
this pr fixes issue #23  Check the attached screenshot
> feat: Add responsive behaviour

- js/script.js
Updated the code according to the recent change in the main.
Closes #27
> Captcha and input be reset after submission

- index.html
- styles/style.css
#44 I have created the nav bar , please merge it.
> New branch nav bar complete

- js/script.js
Here for every 25 seconds the captcha be reloaded and the input box be cleared as well.
Closes #43
> Reload the captcha for every 25seconds

- js/script.js
fixed #26 
Changed the captcha generating logic in order to handle "undefined", also ran it in a loop to make it more efficient.
> fixes undefined issue

- index.html
- styles/style.css
I have added the same footer to Home Page as its in the About page. 
This is how it looks.
> Add footer to home page

- about.html
- package-lock.json
- styles/about.css
I added a bit of styling to it and made it responsive as well hope you like it
> Added stylings to about page

- index.html
- js/script.js
- styles/style.css
Fixes #69
Added Math Captcha Feature
Implemented an option to choose between text and math captcha.
> Added Math Captcha

- index.html
- js/script.js
- styles/style.css
Reverts AdityaSinha2305/ForkTheCaptcha#80
> Revert "added more security"

- about.html
- index.html
> Add GitHub link

- login.html
Made the UI of the Login Page and set the Theme to DARK mode. If any changes.
> Enhancement in the Login Page UI.

- index.html
- js/script.js
- styles/style.css
Fixes #89 
Added Countdown Timer and added alert when time is up.
> Added Countdown Timer

- login.html
**Description**:
- **Reference**: Fixes #96
- **Summary of Changes**: Added a "Sign up" link below the "Submit" button on the login page. This link redirects users to the signup page, enhancing the user experience for new users who don’t have an account.
- **Additional Info**: Styled the link to match the existing theme for a cohesive look and feel.
> Fixes #96 : Add signup feature in login page and redirect to signup page

- index.html
- js/script.js
- styles/style.css
Issue #65 
Added visitors count feature and gave it styling.
> Visitors Count Added #65

- index.html
- js/script.js
- styles/style.css
issue #65 
Global visitor counter added
> Global Visitors Counter added

- js/login.js
- js/signup.js
- signup.html
At first the user needs to signup with basic details and after clicking on the submit button they will be redirected to the login page and giving the same details as given during signup the user will be able to login to the website after displaying a successful message. It will be taking local storage to verify the details of the user credentials of the signup and login page. Proper email and password validation is done along with some changes in the UI with the help of tailwind CSS cdn . Please @AdityaSinha2305 check the changes and merge it . Issue #106
> Fixed the login and signup Page properly
